apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: restrict-attach-pods-clusterrole
rules:
  - apiGroups: ["*"]
    resources: ["pods/attach"]
    verbs: ["get"]
  - apiGroups: ["*"]
    resources: ["pods"]
    verbs: ["get"]