apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: restrict-privilege-escalation-for-node-proxy-clusterrole
rules:
- apiGroups: ["*"]
  resources: ["nodes/proxy"]
  verbs: ["get", "create"]
