apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-privilege-escalation-for-node-proxy-clusterrole
spec:
  validationActions: [Deny]
status:
  conditions:
  - reason: Succeeded
    status: "True"
    type: Ready