apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-impersonating-groups-roles
spec:
  validationActions: [Deny]
status:
  conditions:
  - reason: Succeeded
    status: "True"
    type: Ready